using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.CodeAnalysis;

namespace BlazorWith3d.Unity.CodeGenerator;

internal static class HelloSourceGenerator_BlazorBinding
{
    
    internal static string GenerateBindingClass(TypeInfo bindingType, ITypeSymbol mainInterfaceType, INamedTypeSymbol invokerInterfaceType, INamedTypeSymbol eventHandlerInterfaceType)
    {
        IReadOnlyList<string> namespacesToInclude = new[]{bindingType.@namespace,
            mainInterfaceType.ContainingNamespace.ToDisplayString(),
             invokerInterfaceType.ContainingNamespace.ToDisplayString(),
              eventHandlerInterfaceType.ContainingNamespace.ToDisplayString(),
        };

        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLines(namespacesToInclude.Distinct().Select(o => $"using {o};"));
        sb.AppendLine("using BlazorWith3d.Shared;");
        sb.AppendLine("using Microsoft.JSInterop;");
        sb.AppendLine($"namespace {bindingType.@namespace}");
        using (sb.IndentWithCurlyBrackets())
        {
            sb.AppendLine($"public partial class {bindingType.typeName}: {eventHandlerInterfaceType.Name} ");
            using (sb.IndentWithCurlyBrackets())
            {
                sb.AppendLine($"private {eventHandlerInterfaceType.Name}? _eventHandler;");
                sb.AppendLine($"private IJSObjectReference? _typescriptApp;");

                sb.AppendLine($"public event Action<byte[], Exception> OnMessageError;");

                sb.AppendLine($"public void SetTypescriptApp(IJSObjectReference typescriptApp)");
                using (sb.IndentWithCurlyBrackets())
                {

                    sb.AppendLine($"_typescriptApp=typescriptApp;");
                }

                sb.AppendLine($"public void SetEventHandler({eventHandlerInterfaceType.Name}? eventHandler)");
                using (sb.IndentWithCurlyBrackets())
                {

                    sb.AppendLine($"_eventHandler=eventHandler;");
                }

                foreach (var member in invokerInterfaceType.GetMembers())
                {
                    if (member is IMethodSymbol methodSymbol)
                    {
                        if ((methodSymbol.ReturnType as INamedTypeSymbol).Name != "ValueTask")
                        {
                            throw new InvalidOperationException();
                        }

                        var returnType = (methodSymbol.ReturnType as INamedTypeSymbol).TypeArguments.FirstOrDefault()?.Name;

                        sb.AppendLine($"public {methodSymbol.ReturnType} {methodSymbol.Name}({string.Join(", ", methodSymbol.Parameters.Select(p => $"{p.Type.Name} {p.Name}"))})");
                        using (sb.IndentWithCurlyBrackets())
                        {

                            var jsMethodName = methodSymbol.Name.StartsWith("Invoke") ? $"On{methodSymbol.Name.Substring("Invoke".Length)}" : throw new InvalidOperationException();
                            sb.AppendLine($"return _typescriptApp.Invoke{(returnType == null ? "Void" : "")}Async{(returnType != null ? $"<{returnType}>" : "")}(\"{jsMethodName}\", {string.Join(", ", methodSymbol.Parameters.Select(p => p.Name))});");
                        }
                    }
                }

                foreach (var member in eventHandlerInterfaceType.GetMembers())
                {
                    if (member is IMethodSymbol methodSymbol)
                    {
                        if ((methodSymbol.ReturnType as INamedTypeSymbol).Name != "ValueTask")
                        {
                            throw new InvalidOperationException();
                        }

                        var returnType = (methodSymbol.ReturnType as INamedTypeSymbol).TypeArguments.FirstOrDefault()?.Name;


                        
                        sb.AppendLine($"[JSInvokable]");
                        sb.AppendLine($"public {methodSymbol.ReturnType} {methodSymbol.Name}({string.Join(", ", methodSymbol.Parameters.Select(p => $"{p.Type.Name} {p.Name}"))})");
                        using (sb.IndentWithCurlyBrackets())
                        {
                            sb.AppendLine($"return _eventHandler.{methodSymbol.Name}({string.Join(", ", methodSymbol.Parameters.Select(p => p.Name))});");
                        }
                    }
                }

            }

        }

        return sb.ToString();
    }

}