using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.CodeAnalysis;

namespace BlazorWith3d.Unity.CodeGenerator;

internal static class HelloSourceGenerator_BlazorBinding
{
    
    internal static string GenerateBindingClass(TypeInfo bindingType, AppInfo renderer)
    {
        IReadOnlyList<string> namespacesToInclude = new[] { bindingType.@namespace }
            .Concat(renderer?.namespacesToInclude ?? Enumerable.Empty<string>())
            .Distinct()
            .ToList();

        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLines(namespacesToInclude.Distinct().Select(o => $"using {o};"));
        sb.AppendLine("using BlazorWith3d.Shared;");
        sb.AppendLine("using Microsoft.JSInterop;");
        sb.AppendLine($"namespace {bindingType.@namespace}");
        using (sb.IndentWithCurlyBrackets())
        {
            sb.AppendLine($"public partial class {bindingType.typeName} : {renderer.app.typeName} ");
            using (sb.IndentWithCurlyBrackets())
            {
                sb.AppendLine($"private {renderer.eventHandler.typeName}? _eventHandler;");
                sb.AppendLine($"private IJSObjectReference? _typescriptApp;");
                sb.AppendLine($"private Func<ValueTask>? _onAfterSet{renderer.eventHandlerConceptName};");

                sb.AppendLine($"public event Action<byte[], Exception> OnMessageError;");

                sb.AppendLine();
                sb.AppendLine($"public {bindingType.typeName}(Func<ValueTask>? onAfterSet{renderer.eventHandlerConceptName})");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine($"_onAfterSet{renderer.eventHandlerConceptName} = onAfterSet{renderer.eventHandlerConceptName};");
                }
                
                sb.AppendLine($"public void SetTypescriptApp(IJSObjectReference typescriptApp)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine($"_typescriptApp=typescriptApp;");
                }

                sb.AppendLine($"public async ValueTask Set{renderer.eventHandlerConceptName}({renderer.eventHandler.typeName}{(renderer.eventHandlerNullable?"?":"")} {renderer.eventHandlerConceptName.ToCamelCase()})");
                using (sb.IndentWithCurlyBrackets())
                {

                    sb.AppendLine($"_eventHandler={renderer.eventHandlerConceptName.ToCamelCase()};");
                    sb.AppendLine($"await (_onAfterSet{renderer.eventHandlerConceptName}?.Invoke() ?? new ValueTask());");
                }

                foreach (var m in renderer.methods)
                {

                    sb.AppendLine($"public ValueTask{(m.returnType == null ? "" : $"<{m.returnType.typeName}>")} {m.name}({m.arguments.Select(a => $"{a.argType.typeName} {a.argName}").JoinStringWithComma()})");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine($"return _typescriptApp.Invoke{(m.returnType==null ? "Void" : "")}Async{(m.returnType != null ? $"<{m.returnType.typeName}>" : "")}(\"{m.name}\", {m.arguments.Select(a => a.argName).JoinStringWithComma()});");
                    }

                }

                foreach (var e in renderer.events)
                {
                    sb.AppendLine($"[JSInvokable]");
                    sb.AppendLine($"public ValueTask{(e.returnType == null ? "" : $"<{e.returnType.typeName}>")} {e.name}({e.arguments.Select(a => $"{a.argType.typeName} {a.argName}").JoinStringWithComma()})");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine($"return _eventHandler.{e.name}({e.arguments.Select(a => a.argName).JoinStringWithComma()});");
                    }

                }

            }

        }

        return sb.ToString();
    }

}