using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.CodeAnalysis;

namespace BlazorWith3d.Unity.CodeGenerator;

internal static class HelloSourceGenerator_DotnetApis
{
    internal static string GenerateClass( AppInfo info)
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLines(info.namespacesToInclude.Distinct().Select(o => $"using {o};"));
        sb.AppendLine("using BlazorWith3d.Shared;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using MemoryPack.Formatters;");
        sb.AppendLine($"namespace {info.app.@namespace}");
        using (sb.IndentWithCurlyBrackets())
        {

            var eventHandlerVarName = info.eventHandlerConceptName.ToCamelCase();

            sb.AppendLine($"public partial interface {info.app.typeName}");
            using (sb.IndentWithCurlyBrackets())
            {
                sb.AppendLine($"void Set{info.eventHandlerConceptName}({info.eventHandler.typeName}? {info.eventHandlerConceptName.ToCamelCase()});");
            }

            sb.AppendLine();
            sb.AppendLine($"public partial class {info.app.TypeNameWithoutIPrefix}_BinaryApi: {info.app.typeName}, IDisposable");
            using (sb.IndentWithCurlyBrackets())
            {
                sb.AppendLine();
                sb.AppendLine($"private readonly IBinaryApiSerializer _serializer;");
                sb.AppendLine($"private readonly IBinaryApi _binaryApi;");
                sb.AppendLine($"private {info.eventHandler.typeName}? _eventHandler;");
                sb.AppendLine($"private readonly ArrayBufferWriter<byte> _writer = new ArrayBufferWriter<byte>(100);");

                sb.AppendLine($"private byte _requestResponseIdCounter=0;");

                foreach (var m in info.methods.Where(o=>o.returnType!=null))
                {
                    sb.AppendLine($"private Dictionary<byte,TaskCompletionSource<{m.returnType.typeName}>> _response{m.name}Tcs = new();");
                }

                sb.AppendLine();
                sb.AppendLine($"public {info.app.TypeNameWithoutIPrefix}_BinaryApi(IBinaryApi binaryApi, IBinaryApiSerializer serializer)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine($"_serializer = serializer;");

                    sb.AppendLine("_binaryApi = binaryApi;");
                }
                sb.AppendLine($"public bool IsProcessingMessages => _binaryApi.MainMessageHandler == ProcessMessages;");

                sb.AppendLine($"public void Set{info.eventHandlerConceptName}({info.eventHandler.typeName}? {eventHandlerVarName})");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine(
                        "if(_binaryApi.MainMessageHandler != null && _binaryApi.MainMessageHandler != ProcessMessages)");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("throw new InvalidOperationException(\"Somebody else is handling messages!\");");
                    }

                    sb.AppendLine($"_eventHandler={eventHandlerVarName};");
                    sb.AppendLine($"_binaryApi.MainMessageHandler = {eventHandlerVarName}==null?null: ProcessMessages;");
                }

                sb.AppendLine($"public event Action<byte[], Exception> OnMessageError;");

                sb.AppendLine();
                foreach (var (m, i) in info.methods.EnumerateWithIndex())
                {
                    sb.AppendLine($"public async ValueTask{(m.returnType == null ? "" : $"<{m.returnType.typeName}>")} {m.name}({string.Join(", ", m.arguments.Select(a => $"{a.argType.typeName} {a.argName}"))})");

                    using (sb.IndentWithCurlyBrackets())
                    {
                        if (m.returnType == null)
                        {
                            sb.AppendLine($"await SendMessage({i}, null, {string.Join(", ", m.arguments.Select(a => a.argName))});");
                        }
                        else
                        {
                            sb.AppendLine($"byte requestId;");
                            sb.AppendLine($"unchecked");
                            using (sb.IndentWithCurlyBrackets())
                            {
                                sb.AppendLine($"requestId = _requestResponseIdCounter++;");
                            }

                            sb.AppendLine($"var tcs= new TaskCompletionSource<{m.returnType.typeName}>();");
                            sb.AppendLine($"_response{m.name}Tcs[requestId]=tcs;");

                            sb.AppendLine($"await SendMessage({i}, requestId, {m.arguments.Select(a => a.argName).JoinStringWithComma()});");


                            sb.AppendLine($"var response=await tcs.Task;");
                            sb.AppendLine($"_response{m.name}Tcs.Remove(requestId);");
                            sb.AppendLine($"return response;");
                        }
                    }
                }

                sb.AppendLine();
                sb.AppendLine($"public void Dispose()");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine($"Set{info.eventHandlerConceptName}(null);");
                }

                var methodParamCounts = info.methods.Select(m => m.arguments.Length).Distinct().OrderBy(o=>o);
                foreach(var paramCount in methodParamCounts)
                {
                    var argIndices = Enumerable.Range(0, paramCount);
                    sb.AppendLine();
                    sb.AppendLine($"protected ValueTask SendMessage<{argIndices.Select(gt => $"T{gt}").JoinStringWithComma()}>(byte messageId, byte? requestId,  {argIndices.Select(gt => $"T{gt} arg{gt}").JoinStringWithComma()})");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("try");
                        using (sb.IndentWithCurlyBrackets())
                        {
                            sb.AppendLine("_writer.Clear();");

                            sb.AppendLine("Span<byte> messageIdSpan = stackalloc byte[requestId==null?1:2];");
                            sb.AppendLine("messageIdSpan[0] = messageId;");
                            sb.AppendLine("if(requestId!=null) messageIdSpan[1] = requestId.Value;");
                            sb.AppendLine("_writer.Write(messageIdSpan);");

                            foreach(var argIndex in argIndices)
                            {
                                sb.AppendLine($"_serializer.SerializeObject(arg{argIndex}, _writer);");
                            }

                            sb.AppendLine("var encodedMessage = _writer.WrittenSpan.ToArray();");
                            sb.AppendLine($"return _binaryApi.SendMessage(encodedMessage);");
                        }
                        sb.AppendLine("catch (Exception ex)");

                        using (sb.IndentWithCurlyBrackets())
                        {
                            sb.AppendLine("throw;");
                        }
                    }
                }

                var eventParamCoutns = info.events.Select(m => m.arguments.Length).Distinct().OrderBy(o => o);
                foreach (var paramCount in eventParamCoutns)
                {
                    var argIndices = Enumerable.Range(0, paramCount);
                    sb.AppendLine();
                    sb.AppendLine($"protected {argIndices.Select(i => $"T{i}").JoinStringWithComma().WrapWithParenthesis(paramCount>1)} DeserializeObjectWithoutHeader<{argIndices.Select(i => $"T{i}").JoinStringWithComma()}>(byte[] message, int headerLength)");
                    using (sb.IndentWithCurlyBrackets())
                    {

                        sb.AppendLine($"var currentIndex=headerLength;");
                        sb.AppendLine($"int readCount;");
                        sb.AppendLine($"ReadOnlySpan<byte> span;");
                        foreach (var i in argIndices)
                        {
                            sb.AppendLine($"span = new ReadOnlySpan<byte>(message, currentIndex, message.Length-currentIndex);");
                            sb.AppendLine($"var arg{i}= _serializer.DeserializeObject<T{i}>(span, out readCount);");
                            sb.AppendLine($"currentIndex+=readCount;");
                        }
                        sb.AppendLine($"return {argIndices.Select(i => $"arg{i}").JoinStringWithComma().WrapWithParenthesis(paramCount > 1)};");
                    }
                }

                sb.AppendLine($"protected async ValueTask ProcessMessages(byte[] message)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine("try");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("switch(message[0])");
                        using (sb.IndentWithCurlyBrackets())
                        {
                            foreach (var (e, i) in info.events.EnumerateWithIndex())
                            {
                                sb.AppendLine($"case {i}:");
                                using (sb.IndentWithCurlyBrackets())
                                {
                                    if (e.returnType != null)
                                    {
                                        sb.AppendLine($"var requestId = message[1];");
                                        sb.AppendLine($"var headerLength = 2;");

                                    }
                                    else
                                    {

                                        sb.AppendLine($"var headerLength = 1;");
                                    }
                                        sb.AppendLine($"var {e.arguments.Select((a, i) => $"arg{i}").JoinStringWithComma().WrapWithParenthesis(e.arguments.Length > 1)} = DeserializeObjectWithoutHeader<{e.arguments.Select(a => a.argType.typeName).JoinStringWithComma()}>(message,headerLength);");
                                    sb.AppendLine($"{(e.returnType==null?"":"var response = ")}await _eventHandler.{e.name}({e.arguments.Select((a, i) => $"arg{i}").JoinStringWithComma()});");

                                    if (e.returnType != null)
                                    {
                                        sb.AppendLine($"await SendMessage({i + info.methods.Count}, requestId, response);");
                                    }

                                    sb.AppendLine($"break;");
                                }
                            }
                            foreach (var (m, i) in info.methods.EnumerateWithIndex())
                            {
                                if (m.returnType == null)
                                {
                                    continue;
                                }

                                sb.AppendLine($"case {i + info.events.Count}:");
                                using (sb.IndentWithCurlyBrackets())
                                {
                                    sb.AppendLine($"var requestId = message[1];");
                                    sb.AppendLine($"var obj = DeserializeObjectWithoutHeader<{m.returnType.typeName}>(message,2);");
                                    sb.AppendLine($"_response{m.name}Tcs[requestId].SetResult(obj);");
                                    sb.AppendLine($"break;");
                                }
                            }
                        }
                    }
                    sb.AppendLine("catch (Exception ex)");

                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("OnMessageError?.Invoke(message, ex);");
                        sb.AppendLine("throw;");
                    }
                }
            }


            sb.AppendLine();
            sb.AppendLine($"public partial class {info.app.TypeNameWithoutIPrefix}_BinaryApiWithResponse: {info.app.typeName}, IDisposable");
            using (sb.IndentWithCurlyBrackets())
            {
                sb.AppendLine();
                sb.AppendLine($"private readonly IBinaryApiSerializer _serializer;");
                sb.AppendLine($"private readonly IBinaryApiWithResponse _binaryApi;");
                sb.AppendLine($"private {info.eventHandler.typeName}? _eventHandler;");
                sb.AppendLine($"private readonly ArrayBufferWriter<byte> _writer = new ArrayBufferWriter<byte>(100);");

                sb.AppendLine();
                sb.AppendLine($"public {info.app.TypeNameWithoutIPrefix}_BinaryApiWithResponse(IBinaryApiWithResponse binaryApi, IBinaryApiSerializer serializer)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine($"_serializer = serializer;");

                    sb.AppendLine("_binaryApi = binaryApi;");
                }
                sb.AppendLine($"public bool IsProcessingMessages => _binaryApi.MainMessageHandler == ProcessMessages;");

                sb.AppendLine($"public void Set{info.eventHandlerConceptName}({info.eventHandler.typeName}? {eventHandlerVarName})");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine(
                        "if(_binaryApi.MainMessageHandler != null && _binaryApi.MainMessageHandler != ProcessMessages)");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("throw new InvalidOperationException(\"Somebody else is handling messages!\");");
                    }

                    sb.AppendLine($"_eventHandler={eventHandlerVarName};");
                    sb.AppendLine($"_binaryApi.MainMessageHandler = {eventHandlerVarName}==null?null: ProcessMessages;");
                    sb.AppendLine($"_binaryApi.MainMessageWithResponseHandler = {eventHandlerVarName}==null?null: ProcessMessagesWithResponse;");
                }

                sb.AppendLine($"public event Action<byte[], Exception> OnMessageError;");

                sb.AppendLine();
                foreach (var (m, i) in info.methods.EnumerateWithIndex())
                {
                    sb.AppendLine($"public async ValueTask{(m.returnType == null ? "" : $"<{m.returnType.typeName}>")} {m.name}({string.Join(", ", m.arguments.Select(a => $"{a.argType.typeName} {a.argName}"))})");

                    using (sb.IndentWithCurlyBrackets())
                    {
                        if (m.returnType == null)
                        {
                            sb.AppendLine($"var encodedMessage=SerializeMessage({i}, {string.Join(", ", m.arguments.Select(a => a.argName))});");
                            sb.AppendLine($"await _binaryApi.SendMessage(encodedMessage);");
                        }
                        else
                        {
                            sb.AppendLine($"var encodedMessage=SerializeMessage({i}, {string.Join(", ", m.arguments.Select(a => a.argName))});");
                            sb.AppendLine($"var responseMessage=await _binaryApi.SendMessageWithResponse(encodedMessage);");
                            sb.AppendLine($"var response=_serializer.DeserializeObject<{m.returnType.typeName}>(responseMessage, out var _);");
                            sb.AppendLine($"return response;");
                        }
                    }
                }

                sb.AppendLine();
                sb.AppendLine($"public void Dispose()");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine($"Set{info.eventHandlerConceptName}(null);");
                }




                var methodParamCounts = info.methods.Select(m =>  m.arguments.Length).Distinct().OrderBy(o => o);
                foreach (var paramCount in methodParamCounts)
                {
                    var argIndices = Enumerable.Range(0, paramCount);
                    sb.AppendLine();
                    sb.AppendLine($"protected byte[] SerializeMessage<{argIndices.Select(gt => $"T{gt}").JoinStringWithComma()}>(byte messageId, {argIndices.Select(gt => $"T{gt} arg{gt}").JoinStringWithComma()})");
                    using (sb.IndentWithCurlyBrackets())
                    {
                            sb.AppendLine("_writer.Clear();");
                            sb.AppendLine("Span<byte> messageIdSpan = stackalloc byte[1];");
                            sb.AppendLine("messageIdSpan[0] = messageId;");
                            sb.AppendLine("_writer.Write(messageIdSpan);");


                            foreach (var argIndex in argIndices)
                            {
                                sb.AppendLine($"_serializer.SerializeObject(arg{argIndex}, _writer);");
                            }

                        sb.AppendLine("var encodedMessage = _writer.WrittenSpan.ToArray();");

                        sb.AppendLine("return encodedMessage;");

                    }

                }

                sb.AppendLine();
                sb.AppendLine($"protected byte[] SerializeResponse<TMessage>(TMessage message)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine("_writer.Clear();");
                    sb.AppendLine("_serializer.SerializeObject(message, _writer);");
                    sb.AppendLine("return _writer.WrittenSpan.ToArray();");
                }


                var eventParamCoutns = info.events.Select(m => m.arguments.Length).Distinct().OrderBy(o => o);
                foreach (var paramCount in eventParamCoutns)
                {
                    var argIndices = Enumerable.Range(0, paramCount);
                    sb.AppendLine();
                    sb.AppendLine($"protected {argIndices.Select(i => $"T{i}").JoinStringWithComma().WrapWithParenthesis(paramCount > 1)} DeserializeObjectWithoutHeader<{argIndices.Select(i => $"T{i}").JoinStringWithComma()}>(byte[] message, int headerLength)");
                    using (sb.IndentWithCurlyBrackets())
                    {

                        sb.AppendLine($"var currentIndex=headerLength;");

                        sb.AppendLine($"int readCount;");
                        sb.AppendLine($"ReadOnlySpan<byte> span;");
                        foreach (var i in argIndices)
                        {
                            sb.AppendLine($"span = new ReadOnlySpan<byte>(message, currentIndex, message.Length-currentIndex);");
                            sb.AppendLine($"var arg{i}= _serializer.DeserializeObject<T{i}>(span, out readCount);");
                            sb.AppendLine($"currentIndex+=readCount;");
                        }
                        sb.AppendLine($"return {argIndices.Select(i => $"arg{i}").JoinStringWithComma().WrapWithParenthesis(paramCount > 1)};");
                    }
                }


                sb.AppendLine($"protected async ValueTask ProcessMessages(byte[] message)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine("try");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("switch(message[0])");
                        using (sb.IndentWithCurlyBrackets())
                        {
                            foreach (var (e, i) in info.events.EnumerateWithIndex())
                            {
                                if (e.returnType != null)
                                {
                                    continue;
                                }

                                sb.AppendLine($"case {i}:");
                                using (sb.IndentWithCurlyBrackets())
                                {
                                    sb.AppendLine($"var {e.arguments.Select((a, i) => $"arg{i}").JoinStringWithComma().WrapWithParenthesis(e.arguments.Length > 1)} = DeserializeObjectWithoutHeader<{e.arguments.Select(a => a.argType.typeName).JoinStringWithComma()}>(message,1);");
                                    sb.AppendLine($"await _eventHandler.{e.name}({e.arguments.Select((a, i) => $"arg{i}").JoinStringWithComma()});");
                                    sb.AppendLine($"break;");
                                }
                            }
                        }
                    }
                    sb.AppendLine("catch (Exception ex)");

                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("OnMessageError?.Invoke(message, ex);");
                        sb.AppendLine("throw;");
                    }
                }

                sb.AppendLine($"protected async ValueTask<byte[]> ProcessMessagesWithResponse(byte[] message)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine("try");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("switch(message[0])");
                        using (sb.IndentWithCurlyBrackets())
                        {
                            foreach (var (e, i) in info.events.EnumerateWithIndex())
                            {
                                if (e.returnType == null)
                                {
                                    continue;
                                }

                                sb.AppendLine($"case {i}:");
                                using (sb.IndentWithCurlyBrackets())
                                {
                                    sb.AppendLine($"var {e.arguments.Select((a, i) => $"arg{i}").JoinStringWithComma().WrapWithParenthesis(e.arguments.Length > 1)} = DeserializeObjectWithoutHeader<{e.arguments.Select(a => a.argType.typeName).JoinStringWithComma()}>(message,1);");
                                    sb.AppendLine($"var response = await _eventHandler.{e.name}({e.arguments.Select((a, i) => $"arg{i}").JoinStringWithComma()});");
                                    sb.AppendLine("var responseMessage = SerializeResponse(response);");
                                    sb.AppendLine($"return responseMessage;");

                                    sb.AppendLine($"break;");
                                }
                            }
                        }

                        sb.AppendLine($"throw new InvalidOperationException(\"Missing hanlder for message {{message[0]}}\");");
                    }
                    sb.AppendLine("catch (Exception ex)");

                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("OnMessageError?.Invoke(message, ex);");
                        sb.AppendLine("throw;");
                    }
                }
            }
        }

        return sb.ToString();
    }

}