    // <auto-generated/>

using System;
using System.Threading.Tasks;
using BlazorWith3d.Unity.Shared;
using MemoryPack;

namespace BlazorWith3d.ExampleApp.Client.Unity.Shared
{
#if COMMON_DOTNET || UNITY_EDITOR
    [Blazor3DApp]
#endif
    public partial interface IBlocksOnGrid3DApp
    {
        public event Action<PerfCheckResponse> OnPerfCheckResponse;
        public event Action<AppInitialized> OnAppInitialized;
        public event Action<BlockPoseChangingMessage> OnBlockPoseChangingMessage;
        public event Action<BlockPoseChangedMessage> OnBlockPoseChangedMessage;

        Task InvokePerfCheckRequest(PerfCheckRequest request);
        Task InvokeAddBlockTemplateMessage(AddBlockTemplateMessage request);
        Task InvokeAddBlockInstanceMessage(AddBlockInstanceMessage request);
        Task InvokeRemoveBlockMessage(RemoveBlockMessage request);
        Task InvokeRemoveBlockTemplateMessage(RemoveBlockTemplateMessage request);
        Task InvokeStartDraggingBlockMessage(StartDraggingBlockMessage request);
        Task InvokeBlockPoseChangingResponse(BlockPoseChangingResponse request);
    }


    [Unity3DApp(typeof(IBlocksOnGrid3DApp))]
    public partial interface IBlocksOnGridUnityApi
    {
    }

    [MemoryPackable]
     public partial class PerfCheckRequest 
     {
         public float Aaa;
         public double Bbb;
         public decimal Ccc;
         public string? Ddd;
         public int Id;
     }

    [MemoryPackable]
     public partial class PerfCheckResponse 
     {
         public float Aaa;
         public double Bbb;
         public decimal Ccc;
         public string? Ddd;
         public int Id;
     }

    [MemoryPackable]
     public partial class AppInitialized 
     {
     }

    [MemoryPackable]
     public partial class AddBlockTemplateMessage 
     {
         public float SizeX;
         public float SizeY;
         public float SizeZ;
         public int TemplateId;
         public string? VisualsUri;
     }
     
    [MemoryPackable]
     public partial class AddBlockInstanceMessage 
     {
         public int BlockId;
         public float PositionX;
         public float PositionY;
         public float RotationZ;
         public int TemplateId;
     }

    [MemoryPackable]
     public partial class RemoveBlockMessage 
     {
         public int BlockId;
     }

    [MemoryPackable]
     public partial class RemoveBlockTemplateMessage 
     {
         public int TemplateId;
     }

    [MemoryPackable]
     public partial class StartDraggingBlockMessage 
     {
         public int BlockId;
         public int TemplateId;
     }

    [MemoryPackable]
     public partial class BlockPoseChangingResponse 
     {
         public int BlockId;
         public int ChangingRequestId;
         public bool IsValid;
         public float NewPositionX;
         public float NewPositionY;
         public float NewRotationZ;
     }

    [MemoryPackable]
     public partial class BlockPoseChangingMessage 
     {
         public int BlockId;
         public int ChangingRequestId;
         public float PositionX;
         public float PositionY;
         public float RotationZ;
     }

    [MemoryPackable]
     public partial class BlockPoseChangedMessage 
     {
         public int BlockId;
         public float PositionX;
         public float PositionY;
         public float RotationZ;
     }
}
