using System.Collections.Generic;
using System.Linq;

namespace BlazorWith3d.CodeGenerator;

internal static class HelloSourceGenerator_BlazorBinding
{
    internal static IEnumerable<(string text, string path)> GenerateBindingClass(TwoWayAppInfoWithOwner info)
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLines(info.NamespacesToInclude.Select(o => $"using {o};"));
        sb.AppendLine("using BlazorWith3d.Shared;");
        sb.AppendLine("using Microsoft.JSInterop;");
        sb.AppendLine($"namespace {info.ownerType.@namespace}");
        using (sb.IndentWithCurlyBrackets())
        {
            sb.AppendLine($"public partial class {info.ownerType.typeName} : {info.app.typeName} ");
            using (sb.IndentWithCurlyBrackets())
            {
                sb.AppendLine($"private {info.eventHandler.typeName} _eventHandler = null!;");
                sb.AppendLine($"private IJSObjectReference _typescriptApp = null!;");
                
                sb.AppendLine($"public void SetTypescriptApp(IJSObjectReference typescriptApp)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine($"_typescriptApp = typescriptApp;");
                }

                sb.AppendLine($"public void SetEventHandler({info.eventHandler.typeName} eventHandler)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine($"_eventHandler = eventHandler;");
                }

                foreach (var m in info.methods)
                {

                    sb.AppendLine($"public ValueTask{(m.returnType == null ? "" : $"<{m.returnType.typeName}>")} {m.name}({m.arguments.Select(a => $"{a.argType.typeName} {a.argName}").JoinStringWithComma()})");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine($"return _typescriptApp.Invoke{(m.returnType==null ? "Void" : "")}Async{(m.returnType != null ? $"<{m.returnType.typeName}>" : "")}(\"{m.name}\", {m.arguments.Select(a => a.argName).JoinStringWithComma()});");
                    }

                }

                foreach (var e in info.events)
                {
                    sb.AppendLine($"[JSInvokable]");
                    sb.AppendLine($"public ValueTask{(e.returnType == null ? "" : $"<{e.returnType.typeName}>")} {e.name}({e.arguments.Where(a=>a.argType.typeName != info.app.typeName).Select(a => $"{a.argType.typeName} {a.argName}").JoinStringWithComma()})");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine($"return _eventHandler.{e.name}({e.arguments.Select(a =>(a.argType.typeName == info.app.typeName? "this" : a.argName)).JoinStringWithComma()});");
                    }

                }

            }

        }

        yield return ($"{info.ownerType.typeName}.g.cs", sb.ToString());
    }

}