using System;
using System.Collections.Generic;
using System.Linq;

namespace BlazorWith3d.CodeGenerator;

internal static class HelloSourceGenerator_DotnetApis
{
    internal static IEnumerable<(string name, string content)> GenerateClass( TwoWayAppInfo info)
    {
        var namespaces = new []
            {
                "System",
                "System.Collections.Generic",
                "System.Threading.Tasks",
                "System.Buffers",
                "BlazorWith3d.Shared",
            }
            .Concat(info.NamespacesToInclude)
            .Distinct();
        
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("");
        sb.AppendLines(namespaces.Select(o => $"using {o};"));
        sb.AppendLine($"namespace {info.app.@namespace}");
        using (sb.IndentWithCurlyBrackets())
        {
            sb.AppendLine();
            sb.AppendLine($"public partial class {info.app.TypeNameWithoutIPrefix}OverBinaryApi: {info.app.typeName}, IDisposable");
            using (sb.IndentWithCurlyBrackets())
            {
                sb.AppendLine();
                sb.AppendLine($"private readonly IBinaryApiSerializer _serializer;");
                sb.AppendLine($"private readonly IBinaryApi _binaryApi;");
                sb.AppendLine($"private {info.eventHandler.typeName} _eventHandler;");
                sb.AppendLine($"private readonly IBufferWriterFactory<byte> _writerFactory;");
                sb.AppendLine($"private bool _setMainMessageHandler;");
                sb.AppendLine($"private bool _disposed;");

                sb.AppendLine();
                sb.AppendLine($"public {info.app.TypeNameWithoutIPrefix}OverBinaryApi(IBinaryApi binaryApi, IBinaryApiSerializer serializer, IBufferWriterFactory<byte> writerFactory, {info.eventHandler.typeName} eventHandler)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine("_binaryApi = binaryApi;");
                    sb.AppendLine($"_serializer = serializer;");
                    sb.AppendLine($"_writerFactory = writerFactory;");
                    sb.AppendLine("if(_binaryApi.MainMessageHandler != null && _binaryApi.MainMessageHandler != ProcessMessages)");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("throw new InvalidOperationException(\"Somebody else is handling messages!\");");
                    }

                    sb.AppendLine($"_eventHandler = eventHandler;");
                    sb.AppendLine($"_setMainMessageHandler = true;");
                    sb.AppendLine($"_binaryApi.MainMessageHandler = ProcessMessages;");
                    sb.AppendLine($"_binaryApi.MainMessageWithResponseHandler = ProcessMessagesWithResponse;");
                }
                sb.AppendLine($"public bool IsProcessingMessages => _binaryApi.MainMessageHandler == ProcessMessages;");

                sb.AppendLine($"public event Action<ArraySegment<byte>, Exception>? OnMessageError;");

                sb.AppendLine();
                foreach (var (m, i) in info.methods.EnumerateWithIndex())
                {
                    sb.AppendLine($"public async ValueTask{(m.returnType == null ? "" : $"<{m.returnType.typeName}>")} {m.name}({string.Join(", ", m.arguments.Select(a => $"{a.argType.typeName} {a.argName}"))})");

                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("if(_disposed)");
                        using (sb.IndentWithCurlyBrackets())
                        {
                            sb.AppendLine($"throw new ObjectDisposedException(\"{info.app.TypeNameWithoutIPrefix}OverBinaryApi\");");
                        }
                        if (m.returnType == null)
                        {
                            sb.AppendLine($"var encodedMessage=SerializeMessage({i}, {string.Join(", ", m.arguments.Where(a=>a.argType.typeName!= info.eventHandler.typeName).Select(a => a.argName))});");
                            sb.AppendLine($"await _binaryApi.SendMessage(encodedMessage);");
                        }
                        else
                        {
                            sb.AppendLine($"var encodedMessage=SerializeMessage({i}, {string.Join(", ", m.arguments.Where(a=>a.argType.typeName!= info.eventHandler.typeName).Select(a => a.argName))});");
                            sb.AppendLine($"var responseMessage=await _binaryApi.SendMessageWithResponse(encodedMessage);");
                            sb.AppendLine($"var response=_serializer.DeserializeObject<{m.returnType.typeName}>(responseMessage, out var _);");
                            sb.AppendLine($"return response;");
                        }
                    }
                }

                sb.AppendLine();
                sb.AppendLine($"public void Dispose()");
                using (sb.IndentWithCurlyBrackets())
                {
                    
                    sb.AppendLine($"_disposed=true;");
                    
                    
                    sb.AppendLine($"if(_setMainMessageHandler)");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine($"_binaryApi.MainMessageHandler = null;");
                        sb.AppendLine($"_binaryApi.MainMessageWithResponseHandler = null;");
                    }
                }

                var methodParamCounts = info.methods.Select(m =>  m.arguments.Length).Distinct().OrderBy(o => o);
                foreach (var paramCount in methodParamCounts)
                {
                    var argIndices = Enumerable.Range(0, paramCount);
                    sb.AppendLine();
                    sb.AppendLine($"protected IBufferWriterWithArraySegment<byte> SerializeMessage<{argIndices.Select(gt => $"T{gt}").JoinStringWithComma()}>(byte messageId, {argIndices.Select(gt => $"T{gt} arg{gt}").JoinStringWithComma()})");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("var writer=_writerFactory.Create();");


                        foreach (var argIndex in argIndices)
                        {
                            sb.AppendLine($"_serializer.SerializeObject(arg{argIndex}, writer);");
                        }
                        sb.AppendLine("writer.Write(messageId);");
                        sb.AppendLine("return writer;");

                    }
                }

                sb.AppendLine();
                sb.AppendLine($"protected IBufferWriterWithArraySegment<byte> SerializeResponse<TMessage>(TMessage message)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine("var writer=_writerFactory.Create();");
                    sb.AppendLine("_serializer.SerializeObject(message, writer);");
                    sb.AppendLine("return writer;");
                }


                var eventParamCoutns = info.events.Select(m => m.arguments.Length).Distinct().OrderBy(o => o);
                foreach (var paramCount in eventParamCoutns)
                {
                    var argIndices = Enumerable.Range(0, paramCount);
                    sb.AppendLine();
                    sb.AppendLine($"protected {argIndices.Select(i => $"T{i}").JoinStringWithComma().WrapWithParenthesis(paramCount > 1)} DeserializeObject<{argIndices.Select(i => $"T{i}").JoinStringWithComma()}>(ArraySegment<byte> message)");
                    using (sb.IndentWithCurlyBrackets())
                    {

                        sb.AppendLine($"var currentIndex=0;");

                        sb.AppendLine($"int readCount;");
                        sb.AppendLine($"ArraySegment<byte> span;");
                        foreach (var i in argIndices)
                        {
                            sb.AppendLine($"span = message.Slice(currentIndex, message.Count-currentIndex);");
                            sb.AppendLine($"var arg{i}= _serializer.DeserializeObject<T{i}>(span, out readCount);");
                            sb.AppendLine($"currentIndex+=readCount;");
                        }
                        sb.AppendLine($"return {argIndices.Select(i => $"arg{i}").JoinStringWithComma().WrapWithParenthesis(paramCount > 1)};");
                    }
                }


                sb.AppendLine($"protected async ValueTask ProcessMessages(ArraySegment<byte> message)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine("try");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("switch(message[message.Count-1])");
                        using (sb.IndentWithCurlyBrackets())
                        {
                            foreach (var (e, i) in info.events.EnumerateWithIndex())
                            {
                                if (e.returnType != null)
                                {
                                    continue;
                                }

                                sb.AppendLine($"case {i}:");
                                using (sb.IndentWithCurlyBrackets())
                                {
                                    var deserializableArguments = e.arguments
                                        .Where(a => a.argType.typeName != info.app.typeName)
                                        .ToList();
                                    
                                    sb.AppendLine($"var {deserializableArguments.Select((a, i) => $"arg{i}").JoinStringWithComma().WrapWithParenthesis(deserializableArguments.Count > 1)} = DeserializeObject<{deserializableArguments.Select(a => a.argType.typeName).JoinStringWithComma()}>(message.Slice(0,message.Count-1));");
                                    
                                    var eventHandlerArgs=new List<string>();
                                    int counter=0;
                                    foreach (var a in e.arguments)
                                    {
                                        if (a.argType.typeName == info.app.typeName)
                                        {
                                            eventHandlerArgs.Add("this");
                                        }
                                        else
                                        {
                                            eventHandlerArgs.Add($"arg{counter}");
                                            counter++;
                                        }
                                    }
                                    
                                    
                                    sb.AppendLine($"await _eventHandler.{e.name}({eventHandlerArgs.JoinStringWithComma()});");
                                    sb.AppendLine($"break;");
                                }
                            }
                        }
                    }
                    sb.AppendLine("catch (Exception ex)");

                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("OnMessageError?.Invoke(message, ex);");
                        sb.AppendLine("throw;");
                    }
                }

                sb.AppendLine($"protected async ValueTask<IBufferWriterWithArraySegment<byte>> ProcessMessagesWithResponse(ArraySegment<byte> message)");
                using (sb.IndentWithCurlyBrackets())
                {
                    sb.AppendLine("try");
                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("switch(message[message.Count-1])");
                        using (sb.IndentWithCurlyBrackets())
                        {
                            foreach (var (e, i) in info.events.EnumerateWithIndex())
                            {
                                if (e.returnType == null)
                                {
                                    continue;
                                }

                                sb.AppendLine($"case {i}:");
                                using (sb.IndentWithCurlyBrackets())
                                {
                                    sb.AppendLine($"var {e.arguments.Select((a, i) => $"arg{i}").JoinStringWithComma().WrapWithParenthesis(e.arguments.Length > 1)} = DeserializeObject<{e.arguments.Select(a => a.argType.typeName).JoinStringWithComma()}>(message.Slice(0,message.Count-1));");
                                    sb.AppendLine($"var response = await _eventHandler.{e.name}({e.arguments.Select((a, i) => $"arg{i}").JoinStringWithComma()});");
                                    sb.AppendLine("var responseMessage = SerializeResponse(response);");
                                    sb.AppendLine($"return responseMessage;");
                                }
                            }
                        }

                        sb.AppendLine($"throw new InvalidOperationException(\"Missing hanlder for message {{message[0]}}\");");
                    }
                    sb.AppendLine("catch (Exception ex)");

                    using (sb.IndentWithCurlyBrackets())
                    {
                        sb.AppendLine("OnMessageError?.Invoke(message, ex);");
                        sb.AppendLine("throw;");
                    }
                }
            }
        }

        yield return ($"{info.app.typeName}.g.cs", sb.ToString());
    }

}